# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attendanceManagementUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(1065, 738)
        Form.setStyleSheet("QWidget #Form{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("QWidget #widget{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.le_queryPara = QtWidgets.QLineEdit(self.widget)
        self.le_queryPara.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.le_queryPara.setObjectName("le_queryPara")
        self.horizontalLayout_2.addWidget(self.le_queryPara)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.dateTimeEdit_begin = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit_begin.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateTimeEdit_begin.setCalendarPopup(True)
        self.dateTimeEdit_begin.setObjectName("dateTimeEdit_begin")
        self.horizontalLayout_2.addWidget(self.dateTimeEdit_begin)
        self.dateTimeEdit_end = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit_end.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateTimeEdit_end.setCalendarPopup(True)
        self.dateTimeEdit_end.setObjectName("dateTimeEdit_end")
        self.horizontalLayout_2.addWidget(self.dateTimeEdit_end)
        self.pb_cj_att = QtWidgets.QPushButton(self.widget)
        self.pb_cj_att.setObjectName("pb_cj_att")
        self.horizontalLayout_2.addWidget(self.pb_cj_att)
        self.pb_uploadAtt = QtWidgets.QPushButton(self.widget)
        self.pb_uploadAtt.setObjectName("pb_uploadAtt")
        self.horizontalLayout_2.addWidget(self.pb_uploadAtt)
        self.pb_query = QtWidgets.QPushButton(self.widget)
        self.pb_query.setObjectName("pb_query")
        self.horizontalLayout_2.addWidget(self.pb_query)
        self.pb_allData = QtWidgets.QPushButton(self.widget)
        self.pb_allData.setObjectName("pb_allData")
        self.horizontalLayout_2.addWidget(self.pb_allData)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tv_attendance = QtWidgets.QTableView(self.widget)
        self.tv_attendance.setAlternatingRowColors(True)
        self.tv_attendance.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tv_attendance.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tv_attendance.setWordWrap(False)
        self.tv_attendance.setObjectName("tv_attendance")
        self.tv_attendance.horizontalHeader().setDefaultSectionSize(200)
        self.tv_attendance.horizontalHeader().setMinimumSectionSize(40)
        self.horizontalLayout.addWidget(self.tv_attendance)
        self.label_image = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image.sizePolicy().hasHeightForWidth())
        self.label_image.setSizePolicy(sizePolicy)
        self.label_image.setMinimumSize(QtCore.QSize(300, 500))
        self.label_image.setMaximumSize(QtCore.QSize(300, 400))
        self.label_image.setText("")
        self.label_image.setScaledContents(True)
        self.label_image.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_image.setObjectName("label_image")
        self.horizontalLayout.addWidget(self.label_image)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_currentPage = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_currentPage.sizePolicy().hasHeightForWidth())
        self.lineEdit_currentPage.setSizePolicy(sizePolicy)
        self.lineEdit_currentPage.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_currentPage.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_currentPage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_currentPage.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_currentPage.setObjectName("lineEdit_currentPage")
        self.horizontalLayout_3.addWidget(self.lineEdit_currentPage)
        self.label_totalPage = QtWidgets.QLabel(self.widget)
        self.label_totalPage.setMinimumSize(QtCore.QSize(30, 0))
        self.label_totalPage.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_totalPage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_totalPage.setObjectName("label_totalPage")
        self.horizontalLayout_3.addWidget(self.label_totalPage)
        self.pb_jumpTo = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_jumpTo.sizePolicy().hasHeightForWidth())
        self.pb_jumpTo.setSizePolicy(sizePolicy)
        self.pb_jumpTo.setMinimumSize(QtCore.QSize(80, 0))
        self.pb_jumpTo.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pb_jumpTo.setObjectName("pb_jumpTo")
        self.horizontalLayout_3.addWidget(self.pb_jumpTo)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pb_prev = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_prev.sizePolicy().hasHeightForWidth())
        self.pb_prev.setSizePolicy(sizePolicy)
        self.pb_prev.setMinimumSize(QtCore.QSize(80, 0))
        self.pb_prev.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pb_prev.setObjectName("pb_prev")
        self.horizontalLayout_3.addWidget(self.pb_prev)
        self.pb_next = QtWidgets.QPushButton(self.widget)
        self.pb_next.setMinimumSize(QtCore.QSize(80, 0))
        self.pb_next.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pb_next.setObjectName("pb_next")
        self.horizontalLayout_3.addWidget(self.pb_next)
        spacerItem5 = QtWidgets.QSpacerItem(320, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.verticalLayout_2.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "请输入查询条件："))
        self.le_queryPara.setPlaceholderText(_translate("Form", "请输入人员名称"))
        self.label.setText(_translate("Form", "起止日期："))
        self.dateTimeEdit_begin.setDisplayFormat(_translate("Form", "yyyy/MM/dd HH:mm:ss"))
        self.dateTimeEdit_end.setDisplayFormat(_translate("Form", "yyyy/MM/dd HH:mm:ss"))
        self.pb_cj_att.setText(_translate("Form", "手动采集设备考勤数据"))
        self.pb_uploadAtt.setText(_translate("Form", "手动上传考勤数据到住建平台"))
        self.pb_query.setText(_translate("Form", "本地查询"))
        self.pb_allData.setText(_translate("Form", "全部数据"))
        self.label_2.setText(_translate("Form", "跳转到第"))
        self.lineEdit_currentPage.setText(_translate("Form", "1"))
        self.label_totalPage.setText(_translate("Form", "/ 1 页"))
        self.pb_jumpTo.setText(_translate("Form", "跳  转"))
        self.pb_prev.setText(_translate("Form", "上一页"))
        self.pb_next.setText(_translate("Form", "下一页"))
import resource_rc
