# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'departmentUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(984, 628)
        Form.setStyleSheet("QWidget #Form{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("QWidget #widget{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.le_departmentID = QtWidgets.QLineEdit(self.widget)
        self.le_departmentID.setObjectName("le_departmentID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_departmentID)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_departmentName = QtWidgets.QLineEdit(self.widget)
        self.le_departmentName.setObjectName("le_departmentName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_departmentName)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.le_departmentDemo = QtWidgets.QLineEdit(self.widget)
        self.le_departmentDemo.setObjectName("le_departmentDemo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_departmentDemo)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.checkBox_forLcd = QtWidgets.QCheckBox(self.widget)
        self.checkBox_forLcd.setObjectName("checkBox_forLcd")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBox_forLcd)
        self.label_num = QtWidgets.QLabel(self.widget)
        self.label_num.setObjectName("label_num")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_num)
        self.lineEdit_num = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_num.setObjectName("lineEdit_num")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_num)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_add = QtWidgets.QPushButton(self.widget)
        self.pb_add.setObjectName("pb_add")
        self.verticalLayout.addWidget(self.pb_add)
        self.pb_update = QtWidgets.QPushButton(self.widget)
        self.pb_update.setObjectName("pb_update")
        self.verticalLayout.addWidget(self.pb_update)
        self.pb_del = QtWidgets.QPushButton(self.widget)
        self.pb_del.setObjectName("pb_del")
        self.verticalLayout.addWidget(self.pb_del)
        self.pb_save = QtWidgets.QPushButton(self.widget)
        self.pb_save.setObjectName("pb_save")
        self.verticalLayout.addWidget(self.pb_save)
        self.pb_esc = QtWidgets.QPushButton(self.widget)
        self.pb_esc.setObjectName("pb_esc")
        self.verticalLayout.addWidget(self.pb_esc)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.le_queryPara = QtWidgets.QLineEdit(self.widget)
        self.le_queryPara.setObjectName("le_queryPara")
        self.horizontalLayout_2.addWidget(self.le_queryPara)
        self.pb_query = QtWidgets.QPushButton(self.widget)
        self.pb_query.setObjectName("pb_query")
        self.horizontalLayout_2.addWidget(self.pb_query)
        self.pb_allData = QtWidgets.QPushButton(self.widget)
        self.pb_allData.setObjectName("pb_allData")
        self.horizontalLayout_2.addWidget(self.pb_allData)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tv_department = QtWidgets.QTableView(self.widget)
        self.tv_department.setAlternatingRowColors(True)
        self.tv_department.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tv_department.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tv_department.setWordWrap(False)
        self.tv_department.setObjectName("tv_department")
        self.tv_department.horizontalHeader().setDefaultSectionSize(200)
        self.verticalLayout_3.addWidget(self.tv_department)
        self.verticalLayout_2.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "部门编号"))
        self.label_2.setText(_translate("Form", "部门名称"))
        self.label_3.setText(_translate("Form", "部门说明"))
        self.label_5.setText(_translate("Form", "LED显示"))
        self.checkBox_forLcd.setText(_translate("Form", "是否在LCD中显示"))
        self.label_num.setText(_translate("Form", "在场人员数"))
        self.lineEdit_num.setText(_translate("Form", "0"))
        self.pb_add.setText(_translate("Form", "增加"))
        self.pb_update.setText(_translate("Form", "修改"))
        self.pb_del.setText(_translate("Form", "删除"))
        self.pb_save.setText(_translate("Form", "保存"))
        self.pb_esc.setText(_translate("Form", "取消"))
        self.label_4.setText(_translate("Form", "请输入查询条件："))
        self.pb_query.setText(_translate("Form", "查  询"))
        self.pb_allData.setText(_translate("Form", "全部数据"))
