# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'faceDeviceUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(809, 628)
        Form.setStyleSheet("QWidget #Form{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("QWidget #widget{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 20, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.le_departmentID = QtWidgets.QLineEdit(self.widget)
        self.le_departmentID.setObjectName("le_departmentID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_departmentID)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_departmentName = QtWidgets.QLineEdit(self.widget)
        self.le_departmentName.setObjectName("le_departmentName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_departmentName)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.radioButton_nomal = QtWidgets.QRadioButton(self.widget)
        self.radioButton_nomal.setObjectName("radioButton_nomal")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.radioButton_nomal)
        self.radioButton_stop = QtWidgets.QRadioButton(self.widget)
        self.radioButton_stop.setObjectName("radioButton_stop")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.radioButton_stop)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.horizontalLayout.addLayout(self.formLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_add = QtWidgets.QPushButton(self.widget)
        self.pb_add.setObjectName("pb_add")
        self.verticalLayout.addWidget(self.pb_add)
        self.pb_update = QtWidgets.QPushButton(self.widget)
        self.pb_update.setObjectName("pb_update")
        self.verticalLayout.addWidget(self.pb_update)
        self.pb_del = QtWidgets.QPushButton(self.widget)
        self.pb_del.setObjectName("pb_del")
        self.verticalLayout.addWidget(self.pb_del)
        self.pb_save = QtWidgets.QPushButton(self.widget)
        self.pb_save.setObjectName("pb_save")
        self.verticalLayout.addWidget(self.pb_save)
        self.pb_esc = QtWidgets.QPushButton(self.widget)
        self.pb_esc.setObjectName("pb_esc")
        self.verticalLayout.addWidget(self.pb_esc)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.le_queryPara = QtWidgets.QLineEdit(self.widget)
        self.le_queryPara.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.le_queryPara.setObjectName("le_queryPara")
        self.horizontalLayout_2.addWidget(self.le_queryPara)
        self.pb_query = QtWidgets.QPushButton(self.widget)
        self.pb_query.setObjectName("pb_query")
        self.horizontalLayout_2.addWidget(self.pb_query)
        self.pb_allData = QtWidgets.QPushButton(self.widget)
        self.pb_allData.setObjectName("pb_allData")
        self.horizontalLayout_2.addWidget(self.pb_allData)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tv_department = QtWidgets.QTableView(self.widget)
        self.tv_department.setAlternatingRowColors(True)
        self.tv_department.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tv_department.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tv_department.setWordWrap(False)
        self.tv_department.setObjectName("tv_department")
        self.tv_department.horizontalHeader().setDefaultSectionSize(200)
        self.verticalLayout_3.addWidget(self.tv_department)
        self.verticalLayout_2.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "设备编号"))
        self.label_2.setText(_translate("Form", "设备名称"))
        self.label_5.setText(_translate("Form", "设备类型"))
        self.label_6.setText(_translate("Form", "安装位置"))
        self.label_7.setText(_translate("Form", "是否启用"))
        self.radioButton_nomal.setText(_translate("Form", "正常使用"))
        self.radioButton_stop.setText(_translate("Form", "停止使用"))
        self.label_8.setText(_translate("Form", "设备IP"))
        self.label_9.setText(_translate("Form", "子网掩码"))
        self.label_10.setText(_translate("Form", "设备网关"))
        self.label_11.setText(_translate("Form", "设备SN"))
        self.label_12.setText(_translate("Form", "设备key"))
        self.label_3.setText(_translate("Form", "TextLabel"))
        self.pb_add.setText(_translate("Form", "增加"))
        self.pb_update.setText(_translate("Form", "修改"))
        self.pb_del.setText(_translate("Form", "删除"))
        self.pb_save.setText(_translate("Form", "保存"))
        self.pb_esc.setText(_translate("Form", "取消"))
        self.label_4.setText(_translate("Form", "请输入查询条件："))
        self.pb_query.setText(_translate("Form", "查  询"))
        self.pb_allData.setText(_translate("Form", "全部数据"))
