# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infoCollectionUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_infoCollectionForm(object):
    def setupUi(self, infoCollectionForm):
        infoCollectionForm.setObjectName("infoCollectionForm")
        infoCollectionForm.setWindowModality(QtCore.Qt.WindowModal)
        infoCollectionForm.resize(998, 758)
        infoCollectionForm.setStyleSheet("")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(infoCollectionForm)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.info_main = QtWidgets.QWidget(infoCollectionForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_main.sizePolicy().hasHeightForWidth())
        self.info_main.setSizePolicy(sizePolicy)
        self.info_main.setStyleSheet("QWidget #info_main{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.info_main.setObjectName("info_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.info_main)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.info_main)
        self.tabWidget.setStyleSheet("QTabWidget #tabWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("QWidget #tab{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_name = QtWidgets.QLineEdit(self.tab)
        self.le_name.setObjectName("le_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_name)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.le_sex = QtWidgets.QLineEdit(self.tab)
        self.le_sex.setObjectName("le_sex")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_sex)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.le_nation = QtWidgets.QLineEdit(self.tab)
        self.le_nation.setObjectName("le_nation")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_nation)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.le_birthdate = QtWidgets.QLineEdit(self.tab)
        self.le_birthdate.setObjectName("le_birthdate")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_birthdate)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.le_address = QtWidgets.QLineEdit(self.tab)
        self.le_address.setObjectName("le_address")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.le_address)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.le_idNum = QtWidgets.QLineEdit(self.tab)
        self.le_idNum.setObjectName("le_idNum")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.le_idNum)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.le_issue = QtWidgets.QLineEdit(self.tab)
        self.le_issue.setObjectName("le_issue")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.le_issue)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.le_effectedDate = QtWidgets.QLineEdit(self.tab)
        self.le_effectedDate.setObjectName("le_effectedDate")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.le_effectedDate)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.le_expiredDate = QtWidgets.QLineEdit(self.tab)
        self.le_expiredDate.setObjectName("le_expiredDate")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.le_expiredDate)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_cj = QtWidgets.QPushButton(self.tab)
        self.pb_cj.setEnabled(True)
        self.pb_cj.setFlat(False)
        self.pb_cj.setObjectName("pb_cj")
        self.verticalLayout.addWidget(self.pb_cj)
        self.pb_cj1 = QtWidgets.QPushButton(self.tab)
        self.pb_cj1.setObjectName("pb_cj1")
        self.verticalLayout.addWidget(self.pb_cj1)
        self.pb_camera = QtWidgets.QPushButton(self.tab)
        self.pb_camera.setObjectName("pb_camera")
        self.verticalLayout.addWidget(self.pb_camera)
        self.pb_cj_photo = QtWidgets.QPushButton(self.tab)
        self.pb_cj_photo.setObjectName("pb_cj_photo")
        self.verticalLayout.addWidget(self.pb_cj_photo)
        self.pb_uploadPhoto = QtWidgets.QPushButton(self.tab)
        self.pb_uploadPhoto.setFlat(False)
        self.pb_uploadPhoto.setObjectName("pb_uploadPhoto")
        self.verticalLayout.addWidget(self.pb_uploadPhoto)
        self.pb_save_upload = QtWidgets.QPushButton(self.tab)
        self.pb_save_upload.setObjectName("pb_save_upload")
        self.verticalLayout.addWidget(self.pb_save_upload)
        self.pb_upload_person = QtWidgets.QPushButton(self.tab)
        self.pb_upload_person.setObjectName("pb_upload_person")
        self.verticalLayout.addWidget(self.pb_upload_person)
        self.pb_refresh_photo = QtWidgets.QPushButton(self.tab)
        self.pb_refresh_photo.setObjectName("pb_refresh_photo")
        self.verticalLayout.addWidget(self.pb_refresh_photo)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lb_photo = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_photo.sizePolicy().hasHeightForWidth())
        self.lb_photo.setSizePolicy(sizePolicy)
        self.lb_photo.setMinimumSize(QtCore.QSize(200, 200))
        self.lb_photo.setMaximumSize(QtCore.QSize(200, 200))
        self.lb_photo.setText("")
        self.lb_photo.setScaledContents(False)
        self.lb_photo.setObjectName("lb_photo")
        self.horizontalLayout.addWidget(self.lb_photo)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.lb_photo2 = QtWidgets.QLabel(self.tab)
        self.lb_photo2.setMinimumSize(QtCore.QSize(200, 200))
        self.lb_photo2.setMaximumSize(QtCore.QSize(200, 200))
        self.lb_photo2.setText("")
        self.lb_photo2.setObjectName("lb_photo2")
        self.horizontalLayout.addWidget(self.lb_photo2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.lb_photo3 = QtWidgets.QLabel(self.tab)
        self.lb_photo3.setMinimumSize(QtCore.QSize(200, 200))
        self.lb_photo3.setMaximumSize(QtCore.QSize(200, 200))
        self.lb_photo3.setText("")
        self.lb_photo3.setScaledContents(True)
        self.lb_photo3.setObjectName("lb_photo3")
        self.horizontalLayout.addWidget(self.lb_photo3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("QWidget #tab_2{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.tab_2.setObjectName("tab_2")
        self.tableView = QtWidgets.QTableView(self.tab_2)
        self.tableView.setGeometry(QtCore.QRect(0, 10, 811, 381))
        self.tableView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableView.setGridStyle(QtCore.Qt.DotLine)
        self.tableView.setObjectName("tableView")
        self.pb_readall = QtWidgets.QPushButton(self.tab_2)
        self.pb_readall.setGeometry(QtCore.QRect(880, 80, 91, 31))
        self.pb_readall.setObjectName("pb_readall")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_3.addWidget(self.info_main)

        self.retranslateUi(infoCollectionForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(infoCollectionForm)

    def retranslateUi(self, infoCollectionForm):
        _translate = QtCore.QCoreApplication.translate
        infoCollectionForm.setWindowTitle(_translate("infoCollectionForm", "Form"))
        self.label_2.setText(_translate("infoCollectionForm", "姓        名"))
        self.label_3.setText(_translate("infoCollectionForm", "性        别"))
        self.label_4.setText(_translate("infoCollectionForm", "民        族"))
        self.label_5.setText(_translate("infoCollectionForm", "出  生  日  期"))
        self.label_8.setText(_translate("infoCollectionForm", "住        址"))
        self.label_6.setText(_translate("infoCollectionForm", "身  份  证  号"))
        self.label_9.setText(_translate("infoCollectionForm", "发  证  机  关"))
        self.label_7.setText(_translate("infoCollectionForm", "证件有效期开始"))
        self.label_10.setText(_translate("infoCollectionForm", "证件有效期结束"))
        self.pb_cj.setText(_translate("infoCollectionForm", "读身份证信息（中控）"))
        self.pb_cj1.setText(_translate("infoCollectionForm", "读身份证信息"))
        self.pb_camera.setText(_translate("infoCollectionForm", "从摄像头拍照"))
        self.pb_cj_photo.setText(_translate("infoCollectionForm", "从考勤设备拍摄照片"))
        self.pb_uploadPhoto.setText(_translate("infoCollectionForm", "使用电脑中的照片"))
        self.pb_save_upload.setText(_translate("infoCollectionForm", "保存数据到本地"))
        self.pb_upload_person.setText(_translate("infoCollectionForm", "上传人员信息至住建平台"))
        self.pb_refresh_photo.setText(_translate("infoCollectionForm", "刷新考勤设备照片"))
        self.label.setText(_translate("infoCollectionForm", "图片区："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("infoCollectionForm", "人员信息采集"))
        self.pb_readall.setText(_translate("infoCollectionForm", "获取人员列表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("infoCollectionForm", "人员信息列表"))
