# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainForm(object):
    def setupUi(self, mainForm):
        mainForm.setObjectName("mainForm")
        mainForm.setWindowModality(QtCore.Qt.WindowModal)
        mainForm.resize(1179, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainForm.sizePolicy().hasHeightForWidth())
        mainForm.setSizePolicy(sizePolicy)
        mainForm.setMinimumSize(QtCore.QSize(1024, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/resource/ico/main.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainForm.setWindowIcon(icon)
        mainForm.setAutoFillBackground(False)
        mainForm.setStyleSheet("background-color: rgb(229, 225, 222);")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(mainForm)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.header = QtWidgets.QWidget(mainForm)
        self.header.setEnabled(True)
        self.header.setMinimumSize(QtCore.QSize(0, 80))
        self.header.setMaximumSize(QtCore.QSize(16777215, 80))
        self.header.setAutoFillBackground(False)
        self.header.setStyleSheet("background-color: rgb(57, 112, 254);\n"
"\n"
"")
        self.header.setObjectName("header")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_5.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.header)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/ico/resource/ico/sdti.png"))
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.pb_addPerson = QtWidgets.QPushButton(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_addPerson.sizePolicy().hasHeightForWidth())
        self.pb_addPerson.setSizePolicy(sizePolicy)
        self.pb_addPerson.setMinimumSize(QtCore.QSize(150, 80))
        self.pb_addPerson.setMaximumSize(QtCore.QSize(100, 80))
        self.pb_addPerson.setStyleSheet("font: 75 14pt \"微软雅黑\";\n"
"color: rgb(255, 170, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/resource/ico/cj.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_addPerson.setIcon(icon1)
        self.pb_addPerson.setIconSize(QtCore.QSize(60, 60))
        self.pb_addPerson.setFlat(True)
        self.pb_addPerson.setObjectName("pb_addPerson")
        self.horizontalLayout_5.addWidget(self.pb_addPerson)
        self.pb_zjpt = QtWidgets.QPushButton(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_zjpt.sizePolicy().hasHeightForWidth())
        self.pb_zjpt.setSizePolicy(sizePolicy)
        self.pb_zjpt.setMinimumSize(QtCore.QSize(150, 80))
        self.pb_zjpt.setMaximumSize(QtCore.QSize(150, 80))
        self.pb_zjpt.setStyleSheet("font: 75 14pt \"微软雅黑\";\n"
"color: rgb(255, 170, 0);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/resource/ico/zjpt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_zjpt.setIcon(icon2)
        self.pb_zjpt.setIconSize(QtCore.QSize(70, 70))
        self.pb_zjpt.setFlat(True)
        self.pb_zjpt.setObjectName("pb_zjpt")
        self.horizontalLayout_5.addWidget(self.pb_zjpt)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.pb_exitSystem = QtWidgets.QPushButton(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_exitSystem.sizePolicy().hasHeightForWidth())
        self.pb_exitSystem.setSizePolicy(sizePolicy)
        self.pb_exitSystem.setMinimumSize(QtCore.QSize(150, 80))
        self.pb_exitSystem.setMaximumSize(QtCore.QSize(150, 80))
        self.pb_exitSystem.setStyleSheet("font: 75 14pt \"微软雅黑\";\n"
"color: rgb(255, 170, 0);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ico/resource/ico/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_exitSystem.setIcon(icon3)
        self.pb_exitSystem.setIconSize(QtCore.QSize(60, 60))
        self.pb_exitSystem.setFlat(True)
        self.pb_exitSystem.setObjectName("pb_exitSystem")
        self.horizontalLayout_5.addWidget(self.pb_exitSystem)
        spacerItem2 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.header)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(mainForm)
        self.widget_2.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_2.setSizeIncrement(QtCore.QSize(300, 0))
        self.widget_2.setStyleSheet("background-color: rgb(249, 249, 249);\n"
"border-left-color: rgb(121, 121, 121);\n"
"border-radius:5px;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tree_menu = QtWidgets.QTreeWidget(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        self.tree_menu.setFont(font)
        self.tree_menu.setFrameShape(QtWidgets.QFrame.Box)
        self.tree_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tree_menu.setItemsExpandable(True)
        self.tree_menu.setAnimated(True)
        self.tree_menu.setObjectName("tree_menu")
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tree_menu.headerItem().setFont(0, font)
        self.tree_menu.headerItem().setIcon(0, icon)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_menu)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_menu)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        item_0.setFont(0, font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ico/resource/ico/2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/ico/resource/ico/1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item_0.setIcon(0, icon4)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_menu)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_menu)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_menu)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_menu)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout_2.addWidget(self.tree_menu)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.main_content = QtWidgets.QWidget(mainForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_content.sizePolicy().hasHeightForWidth())
        self.main_content.setSizePolicy(sizePolicy)
        self.main_content.setMinimumSize(QtCore.QSize(500, 0))
        self.main_content.setAutoFillBackground(False)
        self.main_content.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"image: url(:/img/resource/img/main.jpg);\n"
"\n"
"")
        self.main_content.setObjectName("main_content")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.main_content)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3.addWidget(self.main_content)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lable_user = QtWidgets.QLabel(mainForm)
        self.lable_user.setObjectName("lable_user")
        self.horizontalLayout_4.addWidget(self.lable_user)
        self.label_company = QtWidgets.QLabel(mainForm)
        self.label_company.setMinimumSize(QtCore.QSize(0, 25))
        self.label_company.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_company.setAlignment(QtCore.Qt.AlignCenter)
        self.label_company.setObjectName("label_company")
        self.horizontalLayout_4.addWidget(self.label_company)
        self.lable_ver = QtWidgets.QLabel(mainForm)
        self.lable_ver.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lable_ver.setObjectName("lable_ver")
        self.horizontalLayout_4.addWidget(self.lable_ver)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(mainForm)
        QtCore.QMetaObject.connectSlotsByName(mainForm)

    def retranslateUi(self, mainForm):
        _translate = QtCore.QCoreApplication.translate
        mainForm.setWindowTitle(_translate("mainForm", "智慧工地系统"))
        self.pb_addPerson.setText(_translate("mainForm", "增加人员"))
        self.pb_zjpt.setText(_translate("mainForm", "平台操作"))
        self.pb_exitSystem.setText(_translate("mainForm", "退出系统"))
        self.tree_menu.headerItem().setText(0, _translate("mainForm", "智慧工地系统"))
        __sortingEnabled = self.tree_menu.isSortingEnabled()
        self.tree_menu.setSortingEnabled(False)
        self.tree_menu.topLevelItem(0).setText(0, _translate("mainForm", "系统设置"))
        self.tree_menu.topLevelItem(0).child(0).setText(0, _translate("mainForm", "系统参数设置"))
        self.tree_menu.topLevelItem(0).child(1).setText(0, _translate("mainForm", "住建平台信息设置"))
        self.tree_menu.topLevelItem(1).setText(0, _translate("mainForm", "日常操作"))
        self.tree_menu.topLevelItem(1).child(0).setText(0, _translate("mainForm", "劳务人员信息采集"))
        self.tree_menu.topLevelItem(1).child(1).setText(0, _translate("mainForm", "劳务人员信息管理"))
        self.tree_menu.topLevelItem(1).child(2).setText(0, _translate("mainForm", "人员考勤数据管理"))
        self.tree_menu.topLevelItem(2).setText(0, _translate("mainForm", "设备管理"))
        self.tree_menu.topLevelItem(2).child(0).setText(0, _translate("mainForm", "考勤设备"))
        self.tree_menu.topLevelItem(2).child(1).setText(0, _translate("mainForm", "显示屏设备"))
        self.tree_menu.topLevelItem(2).child(2).setText(0, _translate("mainForm", "显示屏内容设置"))
        self.tree_menu.topLevelItem(3).setText(0, _translate("mainForm", "LCD显示"))
        self.tree_menu.topLevelItem(4).setText(0, _translate("mainForm", "数据备份"))
        self.tree_menu.topLevelItem(5).setText(0, _translate("mainForm", "操作员管理"))
        self.tree_menu.topLevelItem(5).child(0).setText(0, _translate("mainForm", "系统人员管理"))
        self.tree_menu.topLevelItem(5).child(1).setText(0, _translate("mainForm", "班组信息管理"))
        self.tree_menu.setSortingEnabled(__sortingEnabled)
        self.lable_user.setText(_translate("mainForm", "当前用户：admin"))
        self.label_company.setText(_translate("mainForm", "成都丰盛时代科技有限公司 版权所有"))
        self.lable_ver.setText(_translate("mainForm", "软件版本：V1.0.0"))
import resource_rc
