# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personManagementUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(1039, 818)
        Form.setStyleSheet("QWidget #Form{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("QWidget #widget{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.le_deviceId = QtWidgets.QLineEdit(self.widget)
        self.le_deviceId.setObjectName("le_deviceId")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_deviceId)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_deviceName = QtWidgets.QLineEdit(self.widget)
        self.le_deviceName.setObjectName("le_deviceName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_deviceName)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.le_deviceIP = QtWidgets.QLineEdit(self.widget)
        self.le_deviceIP.setObjectName("le_deviceIP")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.le_deviceIP)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.le_deivceMask = QtWidgets.QLineEdit(self.widget)
        self.le_deivceMask.setObjectName("le_deivceMask")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.le_deivceMask)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.le_deviceGateWay = QtWidgets.QLineEdit(self.widget)
        self.le_deviceGateWay.setObjectName("le_deviceGateWay")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.le_deviceGateWay)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setMinimumSize(QtCore.QSize(200, 200))
        self.label_19.setMaximumSize(QtCore.QSize(200, 200))
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_19)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.le_deviceSN = QtWidgets.QLineEdit(self.widget)
        self.le_deviceSN.setObjectName("le_deviceSN")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_deviceSN)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.le_key = QtWidgets.QLineEdit(self.widget)
        self.le_key.setObjectName("le_key")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_key)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.le_Memo = QtWidgets.QLineEdit(self.widget)
        self.le_Memo.setObjectName("le_Memo")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_Memo)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setObjectName("checkBox")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.checkBox)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setObjectName("radioButton")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.radioButton_2)
        self.label_20 = QtWidgets.QLabel(self.widget)
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.widget)
        self.label_21.setMinimumSize(QtCore.QSize(200, 184))
        self.label_21.setMaximumSize(QtCore.QSize(200, 184))
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.label_21)
        self.horizontalLayout.addLayout(self.formLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_updata = QtWidgets.QPushButton(self.widget)
        self.pb_updata.setObjectName("pb_updata")
        self.verticalLayout.addWidget(self.pb_updata)
        self.pb_replaceIMG = QtWidgets.QPushButton(self.widget)
        self.pb_replaceIMG.setObjectName("pb_replaceIMG")
        self.verticalLayout.addWidget(self.pb_replaceIMG)
        self.pb_del = QtWidgets.QPushButton(self.widget)
        self.pb_del.setObjectName("pb_del")
        self.verticalLayout.addWidget(self.pb_del)
        self.pb_save = QtWidgets.QPushButton(self.widget)
        self.pb_save.setObjectName("pb_save")
        self.verticalLayout.addWidget(self.pb_save)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pb_esc = QtWidgets.QPushButton(self.widget)
        self.pb_esc.setObjectName("pb_esc")
        self.verticalLayout.addWidget(self.pb_esc)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.le_queryPara = QtWidgets.QLineEdit(self.widget)
        self.le_queryPara.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.le_queryPara.setObjectName("le_queryPara")
        self.horizontalLayout_2.addWidget(self.le_queryPara)
        self.pb_query = QtWidgets.QPushButton(self.widget)
        self.pb_query.setObjectName("pb_query")
        self.horizontalLayout_2.addWidget(self.pb_query)
        self.pb_allData = QtWidgets.QPushButton(self.widget)
        self.pb_allData.setObjectName("pb_allData")
        self.horizontalLayout_2.addWidget(self.pb_allData)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tv_device = QtWidgets.QTableView(self.widget)
        self.tv_device.setAlternatingRowColors(True)
        self.tv_device.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tv_device.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tv_device.setWordWrap(False)
        self.tv_device.setObjectName("tv_device")
        self.tv_device.horizontalHeader().setDefaultSectionSize(200)
        self.verticalLayout_3.addWidget(self.tv_device)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "人员编号"))
        self.label_2.setText(_translate("Form", "人员名称"))
        self.label_5.setText(_translate("Form", "性别"))
        self.label_6.setText(_translate("Form", "民族"))
        self.label_8.setText(_translate("Form", "地址"))
        self.label_7.setText(_translate("Form", "出生日期"))
        self.label_10.setText(_translate("Form", "有效期"))
        self.label_9.setText(_translate("Form", "发证机关"))
        self.label_18.setText(_translate("Form", "身份证图"))
        self.label_14.setText(_translate("Form", "部门工组"))
        self.label_11.setText(_translate("Form", "用户类型"))
        self.label_12.setText(_translate("Form", "注册类型"))
        self.label_3.setText(_translate("Form", "住建统一号"))
        self.label_15.setText(_translate("Form", "是否上传"))
        self.checkBox.setText(_translate("Form", "人员信息是否上传到住建平台"))
        self.label_13.setText(_translate("Form", "住建工作号"))
        self.label_17.setText(_translate("Form", "数据状态"))
        self.label_16.setText(_translate("Form", "人员状态"))
        self.radioButton.setText(_translate("Form", "正常状态"))
        self.radioButton_2.setText(_translate("Form", "停用状态"))
        self.label_20.setText(_translate("Form", "人脸识别图"))
        self.pb_updata.setText(_translate("Form", "修改人员信息"))
        self.pb_replaceIMG.setText(_translate("Form", "更换人脸照片"))
        self.pb_del.setText(_translate("Form", "删除"))
        self.pb_save.setText(_translate("Form", "保存"))
        self.pushButton.setText(_translate("Form", "手动上传权限到设备"))
        self.pb_esc.setText(_translate("Form", "取消"))
        self.label_4.setText(_translate("Form", "请输入查询条件："))
        self.pb_query.setText(_translate("Form", "本地数据查询"))
        self.pb_allData.setText(_translate("Form", "本地全部数据"))
        self.pushButton_2.setText(_translate("Form", "从住建平台刷新新增人员"))
        self.pushButton_3.setText(_translate("Form", "从住建平台刷新删除人员"))
