# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sysSetUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(907, 658)
        Form.setStyleSheet("QWidget #Form{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtWidgets.QToolBox(Form)
        self.toolBox.setStyleSheet("QToolBox #toolBox{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.page_jbcs = QtWidgets.QWidget()
        self.page_jbcs.setGeometry(QtCore.QRect(0, 0, 907, 580))
        self.page_jbcs.setStyleSheet("QWidget #page_jbcs{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.page_jbcs.setObjectName("page_jbcs")
        self.label_2 = QtWidgets.QLabel(self.page_jbcs)
        self.label_2.setGeometry(QtCore.QRect(28, 15, 96, 16))
        self.label_2.setObjectName("label_2")
        self.checkBox_zjptYN = QtWidgets.QCheckBox(self.page_jbcs)
        self.checkBox_zjptYN.setEnabled(False)
        self.checkBox_zjptYN.setGeometry(QtCore.QRect(130, 15, 95, 16))
        self.checkBox_zjptYN.setChecked(True)
        self.checkBox_zjptYN.setObjectName("checkBox_zjptYN")
        self.label = QtWidgets.QLabel(self.page_jbcs)
        self.label.setGeometry(QtCore.QRect(28, 43, 72, 16))
        self.label.setObjectName("label")
        self.comboBox_zjptName = QtWidgets.QComboBox(self.page_jbcs)
        self.comboBox_zjptName.setEnabled(False)
        self.comboBox_zjptName.setGeometry(QtCore.QRect(128, 45, 241, 20))
        self.comboBox_zjptName.setObjectName("comboBox_zjptName")
        self.label_3 = QtWidgets.QLabel(self.page_jbcs)
        self.label_3.setGeometry(QtCore.QRect(28, 195, 72, 16))
        self.label_3.setObjectName("label_3")
        self.le_backupUrl = QtWidgets.QLineEdit(self.page_jbcs)
        self.le_backupUrl.setEnabled(False)
        self.le_backupUrl.setGeometry(QtCore.QRect(130, 195, 641, 20))
        self.le_backupUrl.setObjectName("le_backupUrl")
        self.checkBox_htzdclYN = QtWidgets.QCheckBox(self.page_jbcs)
        self.checkBox_htzdclYN.setEnabled(False)
        self.checkBox_htzdclYN.setGeometry(QtCore.QRect(128, 90, 227, 16))
        self.checkBox_htzdclYN.setObjectName("checkBox_htzdclYN")
        self.label_4 = QtWidgets.QLabel(self.page_jbcs)
        self.label_4.setGeometry(QtCore.QRect(28, 163, 84, 16))
        self.label_4.setObjectName("label_4")
        self.le_localServer = QtWidgets.QLineEdit(self.page_jbcs)
        self.le_localServer.setEnabled(False)
        self.le_localServer.setGeometry(QtCore.QRect(130, 163, 641, 20))
        self.le_localServer.setObjectName("le_localServer")
        self.label_5 = QtWidgets.QLabel(self.page_jbcs)
        self.label_5.setGeometry(QtCore.QRect(28, 120, 96, 16))
        self.label_5.setObjectName("label_5")
        self.spinBox_htzkclTime = QtWidgets.QSpinBox(self.page_jbcs)
        self.spinBox_htzkclTime.setEnabled(False)
        self.spinBox_htzkclTime.setGeometry(QtCore.QRect(130, 120, 38, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_htzkclTime.sizePolicy().hasHeightForWidth())
        self.spinBox_htzkclTime.setSizePolicy(sizePolicy)
        self.spinBox_htzkclTime.setObjectName("spinBox_htzkclTime")
        self.layoutWidget = QtWidgets.QWidget(self.page_jbcs)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 430, 176, 43))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_update = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_update.setObjectName("pb_update")
        self.horizontalLayout_2.addWidget(self.pb_update)
        self.pb_save = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_save.setEnabled(False)
        self.pb_save.setObjectName("pb_save")
        self.horizontalLayout_2.addWidget(self.pb_save)
        self.pb_selectPath = QtWidgets.QPushButton(self.page_jbcs)
        self.pb_selectPath.setEnabled(False)
        self.pb_selectPath.setGeometry(QtCore.QRect(130, 221, 75, 23))
        self.pb_selectPath.setObjectName("pb_selectPath")
        self.checkBox_aqmYN = QtWidgets.QCheckBox(self.page_jbcs)
        self.checkBox_aqmYN.setEnabled(False)
        self.checkBox_aqmYN.setGeometry(QtCore.QRect(130, 290, 191, 16))
        self.checkBox_aqmYN.setObjectName("checkBox_aqmYN")
        self.checkBox_photoBdYN = QtWidgets.QCheckBox(self.page_jbcs)
        self.checkBox_photoBdYN.setEnabled(False)
        self.checkBox_photoBdYN.setGeometry(QtCore.QRect(130, 260, 231, 16))
        self.checkBox_photoBdYN.setObjectName("checkBox_photoBdYN")
        self.label_6 = QtWidgets.QLabel(self.page_jbcs)
        self.label_6.setGeometry(QtCore.QRect(30, 330, 81, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page_jbcs)
        self.label_7.setGeometry(QtCore.QRect(30, 370, 81, 16))
        self.label_7.setObjectName("label_7")
        self.le_cjSN = QtWidgets.QLineEdit(self.page_jbcs)
        self.le_cjSN.setEnabled(False)
        self.le_cjSN.setGeometry(QtCore.QRect(130, 330, 181, 20))
        self.le_cjSN.setObjectName("le_cjSN")
        self.le_cjKEY = QtWidgets.QLineEdit(self.page_jbcs)
        self.le_cjKEY.setEnabled(False)
        self.le_cjKEY.setGeometry(QtCore.QRect(130, 370, 181, 20))
        self.le_cjKEY.setObjectName("le_cjKEY")
        self.toolBox.addItem(self.page_jbcs, "")
        self.page_sbcs = QtWidgets.QWidget()
        self.page_sbcs.setGeometry(QtCore.QRect(0, 0, 907, 580))
        self.page_sbcs.setStyleSheet("QWidget #page_myzj{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.page_sbcs.setObjectName("page_sbcs")
        self.checkBox_2 = QtWidgets.QCheckBox(self.page_sbcs)
        self.checkBox_2.setGeometry(QtCore.QRect(50, 50, 231, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.page_sbcs)
        self.checkBox_3.setGeometry(QtCore.QRect(50, 100, 191, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.toolBox.addItem(self.page_sbcs, "")
        self.page_qtcs = QtWidgets.QWidget()
        self.page_qtcs.setGeometry(QtCore.QRect(0, 0, 907, 580))
        self.page_qtcs.setObjectName("page_qtcs")
        self.toolBox.addItem(self.page_qtcs, "")
        self.verticalLayout.addWidget(self.toolBox)

        self.retranslateUi(Form)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "是否联接住建平台"))
        self.checkBox_zjptYN.setText(_translate("Form", "接入住建平台"))
        self.label.setText(_translate("Form", "住建平台选择"))
        self.label_3.setText(_translate("Form", "数据备份目录"))
        self.checkBox_htzdclYN.setText(_translate("Form", "后台自动处理人员及考勤信息上传下载"))
        self.label_4.setText(_translate("Form", "本地服务器地址"))
        self.label_5.setText(_translate("Form", "后台处理时间间隔"))
        self.pb_update.setText(_translate("Form", "修改"))
        self.pb_save.setText(_translate("Form", "保存"))
        self.pb_selectPath.setText(_translate("Form", "选择目录"))
        self.checkBox_aqmYN.setText(_translate("Form", "未带安全帽不允许进场"))
        self.checkBox_photoBdYN.setText(_translate("Form", "人脸照片上传后立即与身份证对比"))
        self.label_6.setText(_translate("Form", "采集设备SN"))
        self.label_7.setText(_translate("Form", "采集设备KEY"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_jbcs), _translate("Form", "系统运行基本参数"))
        self.checkBox_2.setText(_translate("Form", "人脸照片上传后立即与身份证对比"))
        self.checkBox_3.setText(_translate("Form", "未带安全帽不允许进场"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_sbcs), _translate("Form", "设备功能参数"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_qtcs), _translate("Form", "其他参数"))
